import { requireAuth } from "@abge/auth";
import { getApprovalQueue } from "./actions";
import { ApprovalsClient } from "./approvals-client";
import { prisma } from "@abge/database";
import { hasPermission } from "@abge/rbac";

export default async function ApprovalsPage() {
  const session = await requireAuth();

  // If the user does not even have approval.view permission, block the page entirely or just show empty?
  // User instructions say: "A user may access and view a page while lacking permission for specific actions"
  // So we assume the user has `approval.view` if they are here. But let's be safe.
  const canView = session.effectivePermissions.includes("approval.view");
  
  if (!canView) {
    return (
      <div className="flex items-center justify-center h-[50vh]">
        <div className="text-center space-y-2">
          <h2 className="text-xl font-bold text-white">Access Denied</h2>
          <p className="text-sm text-gray-400">You do not have permission to view the approval queue.</p>
        </div>
      </div>
    );
  }

  const approvals = await getApprovalQueue();

  const canApprove = session.effectivePermissions.includes("approval.approve");
  const canReject = session.effectivePermissions.includes("approval.reject");
  const canRequestChanges = session.effectivePermissions.includes("approval.request_changes");

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white">Approval Queue</h1>
        <p className="text-sm text-gray-400 mt-1">Review and approve content generated by the AI engines.</p>
      </div>
      
      <ApprovalsClient 
        initialApprovals={approvals} 
        permissions={{ canApprove, canReject, canRequestChanges }} 
      />
    </div>
  );
}
